In [1]:
import pandas as pd
import numpy as np

In [4]:
messages = pd.read_csv("spam.csv")

In [5]:
messages.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [7]:
ps = PorterStemmer()
wordnet = WordNetLemmatizer()

In [9]:
corpus =[]

for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['Message'][i])#removing all other characters except a toz and AtoZ
    review = review.lower() # Converting to lowercase
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [23]:
# Create Bag of words

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv1 = CountVectorizer(max_features=5000)

x = cv.fit_transform(corpus).toarray()
x1 = cv.fit_transform(corpus).toarray()

In [15]:
y = pd.get_dummies(messages['Category'])
y = y.iloc[:,1].values
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state = 0)

In [30]:
y_train

array([0, 0, 0, ..., 1, 0, 0], dtype=uint8)

In [31]:
# Using Naive Bayes Classifier

from sklearn.naive_bayes import MultinomialNB

spam_detect_model = MultinomialNB().fit(x_train, y_train)

y_pred = spam_detect_model.predict(x_test)

In [32]:
# Evaluation of model

from sklearn.metrics import confusion_matrix, accuracy_score

confusion_m = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(confusion_m)
print(accuracy)

[[940  15]
 [  9 151]]
0.97847533632287


In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfv = TfidfVectorizer()

x = tfv.fit_transform(corpus).toarray()

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state = 0)

In [41]:
# Using Naive Bayes Classifier

from sklearn.naive_bayes import MultinomialNB

spam_detect_model = MultinomialNB().fit(x_train, y_train)

y_pred = spam_detect_model.predict(x_test)

In [42]:
# Evaluation of model

from sklearn.metrics import confusion_matrix, accuracy_score

confusion_m = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(confusion_m)
print(accuracy)

[[955   0]
 [ 34 126]]
0.9695067264573991


In [43]:
from sklearn import svm
spam_detect = svm.SVC(kernel='linear', C=1,gamma= 10).fit(x_train, y_train)
y_pred = spam_detect.predict(x_test)

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score

confusion_m = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print(confusion_m)
print(accuracy)

[[954   1]
 [ 17 143]]
0.9838565022421525


In [46]:
expected = y_test

from sklearn import metrics
print(metrics.classification_report(expected, y_pred))
print(metrics.confusion_matrix(expected, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       955
           1       0.99      0.89      0.94       160

    accuracy                           0.98      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115

[[954   1]
 [ 17 143]]
